name = "coffee-estate-app"
compatibility_date = "2026-06-08"
pages_build_output_dir = "client/dist"

[[d1_databases]]
binding = "DB"
database_name = "coffee-estate-db"
database_id = "4746bef3-940a-44a1-a8ed-56f86f6ae087"
