import { Router } from 'express';
import { db, row, rows } from '../db.js';
import { requireScopedProperty } from '../middleware/context.js';
import { asyncHandler } from '../utils/asyncHandler.js';

const router = Router();
const today = () => new Date().toISOString().slice(0, 10);
const number = (value, name, { positive = false } = {}) => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || (positive ? parsed <= 0 : parsed < 0)) throw Object.assign(new Error(`${name} is invalid`), { status: 400 });
  return parsed;
};

function scope(req) {
  const context = requireScopedProperty(req);
  if (!context.propertyId) throw Object.assign(new Error('Select a property first'), { status: 400 });
  return context;
}
function audit(req) { return String(req.body.created_by || req.body.modified_by || 'Owner').slice(0, 80); }
function owns(table, idName, id, propertyId) {
  return row(`SELECT * FROM ${table} WHERE ${idName}=? AND property_id=?`, [id, propertyId]);
}
function seasonFor(propertyId, seasonId) {
  const season = owns('finance_season', 'season_id', seasonId, propertyId);
  if (!season) throw Object.assign(new Error('Season does not belong to selected property'), { status: 400 });
  return season;
}
function validateCrop(propertyId, cropId) {
  if (!row('SELECT crop_id FROM crop_master WHERE crop_id=? AND property_id=?', [cropId, propertyId])) throw Object.assign(new Error('Crop does not belong to selected property'), { status: 400 });
}
function validateFinanceYield(cropId, varietyId, yieldTypeId) {
  const match = row(`SELECT fyt.finance_yield_type_id FROM finance_yield_type fyt JOIN variety_master vm ON vm.variety_master_id=fyt.variety_master_id JOIN crop_type_master ct ON ct.crop_type_id=vm.crop_type_id WHERE fyt.finance_yield_type_id=? AND vm.variety_master_id=? AND ct.crop_id=?`, [yieldTypeId, varietyId, cropId]);
  if (!match) throw Object.assign(new Error('Yield type, variety and crop do not match'), { status: 400 });
}

const expenseTotalsSql = `SELECT et.expense_code code,et.expense_name name,ROUND(SUM(re.other_expense),2) total FROM running_expenses re JOIN expensetype et ON et.expensetype_id=re.expensetype_id WHERE re.property_id=@propertyId AND re.status='confirmed' AND (@seasonId IS NULL OR re.season_id=@seasonId) GROUP BY et.expensetype_id ORDER BY total DESC`;
function overview(propertyId, seasonId) {
  const params = { propertyId, seasonId: seasonId || null };
  const revenue = row(`SELECT ROUND(COALESCE(SUM(sale_value),0),2) total FROM finance_sale WHERE property_id=@propertyId AND status='confirmed' AND (@seasonId IS NULL OR season_id=@seasonId)`, params)?.total || 0;
  const expenses = row(`SELECT ROUND(COALESCE(SUM(other_expense),0),2) total FROM running_expenses WHERE property_id=@propertyId AND status='confirmed' AND (@seasonId IS NULL OR season_id=@seasonId)`, params)?.total || 0;
  const labour = row(`SELECT ROUND(COALESCE(SUM(total_earned),0),2) earned,ROUND(COALESCE(SUM(advance_paid),0),2) advance,ROUND(COALESCE(SUM(settled_paid),0),2) paid,ROUND(COALESCE(SUM(outstanding_balance),0),2) outstanding FROM finance_wage_period WHERE property_id=@propertyId AND status IN ('finalized','paid') AND (@seasonId IS NULL OR season_id=@seasonId)`, params) || {};
  const vendor = row(`SELECT ROUND(COALESCE(SUM(commission_earned),0),2) earned,ROUND(COALESCE(SUM(paid_amount),0),2) paid,ROUND(COALESCE(SUM(outstanding_balance),0),2) outstanding FROM finance_vendor_period WHERE property_id=@propertyId AND status IN ('finalized','paid') AND (@seasonId IS NULL OR season_id=@seasonId)`, params) || {};
  const stock = rows(`SELECT fyt.finance_yield_type_id,fyt.yield_type_name,vm.variety_name,bu.baseunit_name,ROUND(COALESCE(h.harvested,0),2) harvested,ROUND(COALESCE(s.sold,0),2) sold,ROUND(COALESCE(h.harvested,0)-COALESCE(s.sold,0),2) available FROM finance_yield_type fyt JOIN variety_master vm ON vm.variety_master_id=fyt.variety_master_id JOIN crop_type_master ct ON ct.crop_type_id=vm.crop_type_id JOIN crop_master cm ON cm.crop_id=ct.crop_id JOIN baseunit bu ON bu.baseunit_id=fyt.default_unit_id LEFT JOIN (SELECT finance_yield_type_id,unit_id,SUM(quantity) harvested FROM finance_harvest WHERE property_id=@propertyId AND status='confirmed' AND (@seasonId IS NULL OR season_id=@seasonId) GROUP BY finance_yield_type_id,unit_id) h ON h.finance_yield_type_id=fyt.finance_yield_type_id AND h.unit_id=fyt.default_unit_id LEFT JOIN (SELECT finance_yield_type_id,unit_id,SUM(quantity) sold FROM finance_sale WHERE property_id=@propertyId AND status='confirmed' AND (@seasonId IS NULL OR season_id=@seasonId) GROUP BY finance_yield_type_id,unit_id) s ON s.finance_yield_type_id=fyt.finance_yield_type_id AND s.unit_id=fyt.default_unit_id WHERE cm.property_id=@propertyId AND (COALESCE(h.harvested,0)<>0 OR COALESCE(s.sold,0)<>0) ORDER BY vm.variety_name,fyt.yield_type_name`, params);
  const currentPrices = rows(`SELECT fyt.yield_type_name,vm.variety_name,(SELECT mr.rate FROM finance_market_rate mr WHERE mr.property_id=@propertyId AND mr.finance_yield_type_id=fyt.finance_yield_type_id AND mr.status='active' AND (@seasonId IS NULL OR mr.season_id=@seasonId) ORDER BY date(mr.effective_date) DESC,mr.market_rate_id DESC LIMIT 1) market_rate,(SELECT bo.offered_rate FROM finance_buyer_offer bo WHERE bo.property_id=@propertyId AND bo.finance_yield_type_id=fyt.finance_yield_type_id AND bo.status IN ('active','accepted') AND (@seasonId IS NULL OR bo.season_id=@seasonId) ORDER BY bo.offered_rate DESC LIMIT 1) buyer_offer,(SELECT fs.actual_rate FROM finance_sale fs WHERE fs.property_id=@propertyId AND fs.finance_yield_type_id=fyt.finance_yield_type_id AND fs.status='confirmed' AND (@seasonId IS NULL OR fs.season_id=@seasonId) ORDER BY date(fs.sale_date) DESC,fs.sale_id DESC LIMIT 1) latest_sale FROM finance_yield_type fyt JOIN variety_master vm ON vm.variety_master_id=fyt.variety_master_id JOIN crop_type_master ct ON ct.crop_type_id=vm.crop_type_id JOIN crop_master cm ON cm.crop_id=ct.crop_id WHERE cm.property_id=@propertyId AND (market_rate IS NOT NULL OR buyer_offer IS NOT NULL OR latest_sale IS NOT NULL) ORDER BY vm.variety_name,fyt.yield_type_name`, params);
  return { revenue, expenses, gain: Number((revenue - expenses).toFixed(2)), labour, vendor, stock, currentPrices, expenseBreakdown: rows(expenseTotalsSql, params) };
}

router.get('/overview', asyncHandler((req, res) => {
  const { propertyId } = scope(req); const seasonId = req.query.seasonId ? Number(req.query.seasonId) : null;
  if (seasonId) seasonFor(propertyId, seasonId);
  res.json(overview(propertyId, seasonId));
}));
router.get('/setup', asyncHandler((req, res) => {
  const { propertyId } = scope(req);
  res.json({
    seasons: rows(`SELECT fs.*,cm.crop_name FROM finance_season fs JOIN crop_master cm ON cm.crop_id=fs.crop_id WHERE fs.property_id=? ORDER BY date(fs.start_date) DESC`, [propertyId]),
    cycles: rows(`SELECT * FROM finance_settlement_cycle WHERE property_id=? ORDER BY status,cycle_name`, [propertyId]),
    engagements: rows(`SELECT e.*,l.name labor_name,v.vendorname FROM finance_labour_engagement e JOIN labors l ON l.labor_id=e.labor_id LEFT JOIN vendor v ON v.vendor_id=e.vendor_id WHERE e.property_id=? ORDER BY l.name,date(e.effective_from) DESC`, [propertyId]),
    wageRules: rows(`SELECT wr.*,l.name labor_name,fs.season_name,bu.baseunit_name FROM finance_wage_rule wr JOIN labors l ON l.labor_id=wr.labor_id LEFT JOIN finance_season fs ON fs.season_id=wr.season_id LEFT JOIN baseunit bu ON bu.baseunit_id=wr.variable_unit_id WHERE wr.property_id=? ORDER BY date(wr.effective_from) DESC`, [propertyId]),
    commissionRules: rows(`SELECT cr.*,l.name labor_name,v.vendorname,fs.season_name FROM finance_vendor_commission_rule cr JOIN finance_labour_engagement e ON e.labour_engagement_id=cr.labour_engagement_id JOIN labors l ON l.labor_id=e.labor_id JOIN vendor v ON v.vendor_id=e.vendor_id LEFT JOIN finance_season fs ON fs.season_id=cr.season_id WHERE cr.property_id=? ORDER BY date(cr.effective_from) DESC`, [propertyId]),
    yieldTypes: rows(`SELECT fyt.*,vm.variety_name,ct.type_name,cm.crop_name,bu.baseunit_name FROM finance_yield_type fyt JOIN variety_master vm ON vm.variety_master_id=fyt.variety_master_id JOIN crop_type_master ct ON ct.crop_type_id=vm.crop_type_id JOIN crop_master cm ON cm.crop_id=ct.crop_id JOIN baseunit bu ON bu.baseunit_id=fyt.default_unit_id WHERE cm.property_id=? ORDER BY cm.crop_name,vm.variety_name,fyt.yield_type_name`, [propertyId]),
    buyers: rows(`SELECT vendor_id buyer_id,vendorname buyer_name,description FROM vendor WHERE user_id=(SELECT user_id FROM property WHERE property_id=?) ORDER BY vendorname`, [propertyId])
  });
}));

const listQueries = {
  seasons: `SELECT fs.*,cm.crop_name FROM finance_season fs JOIN crop_master cm ON cm.crop_id=fs.crop_id WHERE fs.property_id=@propertyId ORDER BY date(fs.start_date) DESC`,
  expenses: `SELECT re.*,et.expense_name,et.expense_code,cm.crop_name,b.block_name,wa.work_activity_name,fyt.yield_type_name FROM running_expenses re JOIN expensetype et ON et.expensetype_id=re.expensetype_id LEFT JOIN crop_master cm ON cm.crop_id=re.crop_master_id LEFT JOIN blocks b ON b.block_id=re.block_id LEFT JOIN work_activity wa ON wa.work_activity_id=re.work_activity_id LEFT JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=re.finance_yield_type_id WHERE re.property_id=@propertyId AND (@seasonId IS NULL OR re.season_id=@seasonId) ORDER BY date(re.expense_occurence_date) DESC,re.expense_id DESC`,
  harvests: `SELECT h.*,cm.crop_name,vm.variety_name,fyt.yield_type_name,bu.baseunit_name,b.block_name FROM finance_harvest h JOIN crop_master cm ON cm.crop_id=h.crop_id JOIN variety_master vm ON vm.variety_master_id=h.variety_master_id JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=h.finance_yield_type_id JOIN baseunit bu ON bu.baseunit_id=h.unit_id LEFT JOIN blocks b ON b.block_id=h.block_id WHERE h.property_id=@propertyId AND (@seasonId IS NULL OR h.season_id=@seasonId) ORDER BY date(h.harvest_date) DESC,h.harvest_id DESC`,
  marketRates: `SELECT mr.*,vm.variety_name,fyt.yield_type_name,bu.baseunit_name FROM finance_market_rate mr JOIN variety_master vm ON vm.variety_master_id=mr.variety_master_id JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=mr.finance_yield_type_id JOIN baseunit bu ON bu.baseunit_id=mr.unit_id WHERE mr.property_id=@propertyId AND (@seasonId IS NULL OR mr.season_id=@seasonId) ORDER BY date(mr.effective_date) DESC,mr.market_rate_id DESC`,
  buyerOffers: `SELECT bo.*,v.vendorname buyer_name,vm.variety_name,fyt.yield_type_name,bu.baseunit_name FROM finance_buyer_offer bo JOIN vendor v ON v.vendor_id=bo.buyer_id JOIN variety_master vm ON vm.variety_master_id=bo.variety_master_id JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=bo.finance_yield_type_id JOIN baseunit bu ON bu.baseunit_id=bo.unit_id WHERE bo.property_id=@propertyId AND (@seasonId IS NULL OR bo.season_id=@seasonId) ORDER BY date(bo.offer_date) DESC,bo.offered_rate DESC`,
  sales: `SELECT s.*,v.vendorname buyer_name,vm.variety_name,fyt.yield_type_name,bu.baseunit_name FROM finance_sale s JOIN vendor v ON v.vendor_id=s.buyer_id JOIN variety_master vm ON vm.variety_master_id=s.variety_master_id JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=s.finance_yield_type_id JOIN baseunit bu ON bu.baseunit_id=s.unit_id WHERE s.property_id=@propertyId AND (@seasonId IS NULL OR s.season_id=@seasonId) ORDER BY date(s.sale_date) DESC,s.sale_id DESC`,
  wagePeriods: `SELECT wp.*,l.name labor_name FROM finance_wage_period wp JOIN labors l ON l.labor_id=wp.labor_id WHERE wp.property_id=@propertyId AND (@seasonId IS NULL OR wp.season_id=@seasonId) ORDER BY date(wp.period_end) DESC,wp.wage_period_id DESC`,
  vendorPeriods: `SELECT vp.*,l.name labor_name,v.vendorname FROM finance_vendor_period vp JOIN labors l ON l.labor_id=vp.labor_id JOIN vendor v ON v.vendor_id=vp.vendor_id WHERE vp.property_id=@propertyId AND (@seasonId IS NULL OR vp.season_id=@seasonId) ORDER BY date(vp.period_end) DESC,vp.vendor_period_id DESC`
};
router.get('/:resource', asyncHandler((req, res) => {
  const { propertyId } = scope(req); const query = listQueries[req.params.resource];
  if (!query) return res.status(404).json({ error: 'Unknown finance resource' });
  const seasonId = req.query.seasonId ? Number(req.query.seasonId) : null; if (seasonId) seasonFor(propertyId, seasonId);
  res.json(rows(query, { propertyId, seasonId }));
}));

router.post('/:resource', asyncHandler((req, res) => {
  const { propertyId } = scope(req); const b = req.body; const who = audit(req); let result;
  if (b.season_id) seasonFor(propertyId, Number(b.season_id));
  switch (req.params.resource) {
    case 'seasons': validateCrop(propertyId, Number(b.crop_id)); result=db.prepare(`INSERT INTO finance_season(property_id,crop_id,season_name,start_date,end_date,status,created_by) VALUES(?,?,?,?,?,?,?)`).run(propertyId,b.crop_id,b.season_name,b.start_date,b.end_date,b.status||'planned',who); break;
    case 'cycles': result=db.prepare(`INSERT INTO finance_settlement_cycle(property_id,cycle_name,frequency,custom_days,effective_from,effective_to,created_by) VALUES(?,?,?,?,?,?,?)`).run(propertyId,b.cycle_name,b.frequency,b.custom_days||null,b.effective_from,b.effective_to||null,who); break;
    case 'engagements': result=db.prepare(`INSERT INTO finance_labour_engagement(property_id,labor_id,labour_type,vendor_id,effective_from,effective_to,created_by) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM propertylabor WHERE property_id=? AND labor_id=?)`).run(propertyId,b.labor_id,b.labour_type,b.labour_type==='vendor'?b.vendor_id:null,b.effective_from,b.effective_to||null,who,propertyId,b.labor_id); if(!result.changes) throw new Error('Labour is not assigned to selected property'); break;
    case 'wageRules': result=db.prepare(`INSERT INTO finance_wage_rule(property_id,season_id,labor_id,settlement_cycle_id,effective_from,effective_to,fixed_rate,fixed_basis,variable_rate,variable_unit_id,overtime_rate,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(propertyId,b.season_id||null,b.labor_id,b.settlement_cycle_id||null,b.effective_from,b.effective_to||null,number(b.fixed_rate||0,'Fixed rate'),b.fixed_basis||'day',number(b.variable_rate||0,'Variable rate'),b.variable_unit_id||null,number(b.overtime_rate||0,'Overtime rate'),who); break;
    case 'commissionRules': { const engagement=owns('finance_labour_engagement','labour_engagement_id',b.labour_engagement_id,propertyId); if(!engagement||engagement.labour_type!=='vendor') throw new Error('Select an effective vendor labour engagement'); result=db.prepare(`INSERT INTO finance_vendor_commission_rule(property_id,season_id,labour_engagement_id,effective_from,effective_to,commission_percentage,created_by) VALUES(?,?,?,?,?,?,?)`).run(propertyId,b.season_id||null,b.labour_engagement_id,b.effective_from,b.effective_to||null,number(b.commission_percentage,'Commission'),who); break; }
    case 'yieldTypes': { validateCrop(propertyId,Number(b.crop_id)); result=db.prepare(`INSERT INTO finance_yield_type(variety_master_id,yield_type_name,default_unit_id,created_by) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM variety_master vm JOIN crop_type_master ct ON ct.crop_type_id=vm.crop_type_id WHERE vm.variety_master_id=? AND ct.crop_id=?)`).run(b.variety_master_id,b.yield_type_name,b.default_unit_id,who,b.variety_master_id,b.crop_id); if(!result.changes) throw new Error('Variety does not belong to crop'); break; }
    case 'marketRates': validateCrop(propertyId,Number(b.crop_id)); validateFinanceYield(Number(b.crop_id),Number(b.variety_master_id),Number(b.finance_yield_type_id)); result=db.prepare(`INSERT INTO finance_market_rate(property_id,season_id,crop_id,variety_master_id,finance_yield_type_id,effective_date,rate,unit_id,source_name,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(propertyId,b.season_id||null,b.crop_id,b.variety_master_id,b.finance_yield_type_id,b.effective_date||today(),number(b.rate,'Rate'),b.unit_id,b.source_name||null,b.notes||null,who); break;
    case 'buyerOffers': validateCrop(propertyId,Number(b.crop_id)); validateFinanceYield(Number(b.crop_id),Number(b.variety_master_id),Number(b.finance_yield_type_id)); result=db.prepare(`INSERT INTO finance_buyer_offer(property_id,season_id,crop_id,variety_master_id,finance_yield_type_id,buyer_id,market_rate_id,offered_rate,unit_id,offer_date,valid_until,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(propertyId,b.season_id||null,b.crop_id,b.variety_master_id,b.finance_yield_type_id,b.buyer_id,b.market_rate_id||null,number(b.offered_rate,'Offered rate'),b.unit_id,b.offer_date||today(),b.valid_until||null,b.notes||null,who); break;
    case 'harvests': validateCrop(propertyId,Number(b.crop_id)); validateFinanceYield(Number(b.crop_id),Number(b.variety_master_id),Number(b.finance_yield_type_id)); result=db.prepare(`INSERT INTO finance_harvest(property_id,season_id,crop_id,variety_master_id,finance_yield_type_id,block_id,quantity,unit_id,harvest_date,notes,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(propertyId,b.season_id,b.crop_id,b.variety_master_id,b.finance_yield_type_id,b.block_id||null,number(b.quantity,'Quantity',{positive:true}),b.unit_id,b.harvest_date||today(),b.notes||null,b.status||'confirmed',who); break;
    case 'sales': validateCrop(propertyId,Number(b.crop_id)); validateFinanceYield(Number(b.crop_id),Number(b.variety_master_id),Number(b.finance_yield_type_id)); { const quantity=number(b.quantity,'Quantity',{positive:true}); const rate=number(b.actual_rate,'Actual rate'); result=db.prepare(`INSERT INTO finance_sale(property_id,season_id,crop_id,variety_master_id,finance_yield_type_id,buyer_id,market_rate_id,buyer_offer_id,quantity,unit_id,actual_rate,sale_value,sale_date,payment_status,payment_method,notes,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(propertyId,b.season_id,b.crop_id,b.variety_master_id,b.finance_yield_type_id,b.buyer_id,b.market_rate_id||null,b.buyer_offer_id||null,quantity,b.unit_id,rate,Number((quantity*rate).toFixed(2)),b.sale_date||today(),b.payment_status||'unpaid',b.payment_method||null,b.notes||null,b.status||'confirmed',who); break; }
    case 'expenses': result=db.prepare(`INSERT INTO running_expenses(expensetype_id,property_id,season_id,crop_master_id,block_id,work_activity_id,finance_yield_type_id,expense_code,expense_occurence_date,other_expense,description,payment_status,payment_method,source_type,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'manual','confirmed',?)`).run(b.expensetype_id,propertyId,b.season_id||null,b.crop_id||null,b.block_id||null,b.work_activity_id||null,b.finance_yield_type_id||null,b.description,b.expense_date||today(),number(b.amount,'Amount',{positive:true}),b.description,b.payment_status||'paid',b.payment_method||null,who); break;
    case 'wagePeriods': { const total=number(b.total_earned,'Total earned'); const advance=number(b.advance_paid||0,'Advance'); const paid=number(b.settled_paid||0,'Paid'); const outstanding=Number((total-advance-paid).toFixed(2)); if(outstanding<0) throw new Error('Advance and paid amount cannot exceed total earned'); result=db.prepare(`INSERT INTO finance_wage_period(property_id,season_id,labor_id,wage_rule_id,settlement_cycle_id,period_start,period_end,fixed_earned,variable_earned,overtime_earned,total_earned,advance_paid,settled_paid,outstanding_balance,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(propertyId,b.season_id||null,b.labor_id,b.wage_rule_id,b.settlement_cycle_id||null,b.period_start,b.period_end,number(b.fixed_earned||0,'Fixed earned'),number(b.variable_earned||0,'Variable earned'),number(b.overtime_earned||0,'Overtime earned'),total,advance,paid,outstanding,who); break; }
    case 'vendorPeriods': { const wage=owns('finance_wage_period','wage_period_id',b.wage_period_id,propertyId); const rule=owns('finance_vendor_commission_rule','vendor_commission_rule_id',b.vendor_commission_rule_id,propertyId); if(!wage||!['finalized','paid'].includes(wage.status)||!rule)throw new Error('Select a finalized wage period and matching commission rule'); const engagement=owns('finance_labour_engagement','labour_engagement_id',rule.labour_engagement_id,propertyId); if(!engagement||engagement.labour_type!=='vendor'||Number(engagement.labor_id)!==Number(wage.labor_id))throw new Error('Commission rule does not match the wage labour'); const commission=Number((Number(wage.total_earned)*Number(rule.commission_percentage)/100).toFixed(2)),paid=number(b.paid_amount||0,'Paid amount'); if(paid>commission)throw new Error('Paid amount cannot exceed commission earned'); result=db.prepare(`INSERT INTO finance_vendor_period(property_id,season_id,vendor_id,labor_id,wage_period_id,vendor_commission_rule_id,period_start,period_end,eligible_earnings,commission_percentage,commission_earned,paid_amount,outstanding_balance,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(propertyId,wage.season_id,engagement.vendor_id,wage.labor_id,wage.wage_period_id,rule.vendor_commission_rule_id,wage.period_start,wage.period_end,wage.total_earned,rule.commission_percentage,commission,paid,Number((commission-paid).toFixed(2)),who); break; }
    default: return res.status(404).json({ error: 'Unknown finance resource' });
  }
  res.status(201).json({ id:Number(result.lastInsertRowid) });
}));

router.patch('/:resource/:id', asyncHandler((req,res)=>{
  const {propertyId}=scope(req); const id=Number(req.params.id); const who=audit(req); const action=req.body.action;
  if(action==='archive'){
    const map={seasons:['finance_season','season_id'],cycles:['finance_settlement_cycle','settlement_cycle_id'],wageRules:['finance_wage_rule','wage_rule_id'],commissionRules:['finance_vendor_commission_rule','vendor_commission_rule_id'],marketRates:['finance_market_rate','market_rate_id']};
    const cfg=map[req.params.resource]; if(!cfg)return res.status(400).json({error:'This record cannot be archived here'});
    const result=db.prepare(`UPDATE ${cfg[0]} SET status='archived',modified_on=CURRENT_TIMESTAMP,modified_by=? WHERE ${cfg[1]}=? AND property_id=?`).run(who,id,propertyId); if(!result.changes)return res.status(404).json({error:'Record not found'}); return res.json({ok:true,status:'archived'});
  }
  if(req.params.resource==='wagePeriods'&&action==='finalize'){
    const tx=db.transaction(()=>{ const period=owns('finance_wage_period','wage_period_id',id,propertyId); if(!period||period.status!=='draft')throw new Error('Only a draft wage period can be finalized'); const type=row(`SELECT expensetype_id FROM expensetype WHERE expense_code='LABOUR'`); const expense=db.prepare(`INSERT INTO running_expenses(expensetype_id,property_id,season_id,expense_code,expense_occurence_date,other_expense,description,payment_status,source_type,source_id,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source_type,source_id) WHERE source_type<>'manual' AND source_id IS NOT NULL AND status<>'reversed' DO UPDATE SET other_expense=excluded.other_expense,modified_date=CURRENT_TIMESTAMP,modified_by=excluded.created_by RETURNING expense_id`).get(type.expensetype_id,propertyId,period.season_id,'Labour settlement',period.period_end,period.total_earned,`Labour earning period ${period.period_start} to ${period.period_end}`,period.outstanding_balance>0?'partial':'paid','wage_period',id,'confirmed',who); db.prepare(`UPDATE finance_wage_period SET status=?,expense_id=?,modified_on=CURRENT_TIMESTAMP,modified_by=? WHERE wage_period_id=?`).run(period.outstanding_balance>0?'finalized':'paid',expense.expense_id,who,id); return expense; }); return res.json(tx());
  }
  if(req.params.resource==='vendorPeriods'&&action==='finalize'){
    const tx=db.transaction(()=>{const period=owns('finance_vendor_period','vendor_period_id',id,propertyId);if(!period||period.status!=='draft')throw new Error('Only a draft vendor period can be finalized');const type=row(`SELECT expensetype_id FROM expensetype WHERE expense_code='VENDOR-COMMISSION'`);const expense=db.prepare(`INSERT INTO running_expenses(expensetype_id,property_id,season_id,expense_code,expense_occurence_date,other_expense,description,payment_status,source_type,source_id,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) RETURNING expense_id`).get(type.expensetype_id,propertyId,period.season_id,'Vendor commission',period.period_end,period.commission_earned,`Vendor commission period ${period.period_start} to ${period.period_end}`,period.outstanding_balance>0?'partial':'paid','vendor_period',id,'confirmed',who);db.prepare(`UPDATE finance_vendor_period SET status=?,expense_id=?,modified_on=CURRENT_TIMESTAMP,modified_by=? WHERE vendor_period_id=?`).run(period.outstanding_balance>0?'finalized':'paid',expense.expense_id,who,id);return expense;});return res.json(tx());
  }
  if(['expenses','harvests','sales'].includes(req.params.resource)&&['cancel','reverse'].includes(action)){
    const map={expenses:['running_expenses','expense_id','modified_date'],harvests:['finance_harvest','harvest_id','modified_on'],sales:['finance_sale','sale_id','modified_on']}; const cfg=map[req.params.resource]; const status=action==='reverse'?'reversed':'cancelled'; const result=db.prepare(`UPDATE ${cfg[0]} SET status=?,${cfg[2]}=CURRENT_TIMESTAMP,modified_by=? WHERE ${cfg[1]}=? AND property_id=? AND status IN ('draft','confirmed')`).run(status,who,id,propertyId); if(!result.changes)return res.status(404).json({error:'Active record not found'}); return res.json({ok:true,status});
  }
  res.status(400).json({error:'Unsupported finance action'});
}));

export default router;
