import { json, options, propertyIdFromUrl, userIdFromRequest, assertPropertyAccess, dashboardRange, all, first, fail } from '../_shared/http.js';
export function onRequestOptions() { return options(); }
export async function onRequestGet({ request, env }) {
  try {
    const userId = await userIdFromRequest(request,env);
    const propertyId = propertyIdFromUrl(request);
    if (!propertyId) return json({ error: 'Select a property before viewing dashboard' }, 400);
    await assertPropertyAccess(env, userId, propertyId);
    const attendanceRange = dashboardRange(request, 'attendance');
    const rainfallRange = dashboardRange(request, 'rainfall');
    const yieldRange = dashboardRange(request, 'yield');
    const expenseRange = dashboardRange(request, 'expenses');
    const incomeRange = dashboardRange(request, 'income');
    const assetRange = dashboardRange(request, 'assets');
    const profitRange = dashboardRange(request, 'profit');
    const recentRange = dashboardRange(request, 'recent');
    const workRange = dashboardRange(request, 'work');
    const attendance = await first(env, `SELECT COUNT(*) entries, COALESCE(SUM(attendance_value),0) labor_days FROM attendance WHERE date(entry_date) BETWEEN date(?) AND date(?) AND property_id = ?`, attendanceRange.from, attendanceRange.to, propertyId);
    const laborCost = await first(env, `SELECT ROUND(COALESCE(SUM(a.attendance_value * COALESCE(w.wage_fixed + w.wage_variable,0)),0),2) total FROM attendance a LEFT JOIN wage w ON w.wage_id=(SELECT w2.wage_id FROM wage w2 WHERE w2.labor_id=a.labor_id ORDER BY datetime(COALESCE(w2.modified_on,w2.created_on)) DESC,w2.wage_id DESC LIMIT 1) WHERE date(a.entry_date) BETWEEN date(?) AND date(?) AND a.property_id = ?`, attendanceRange.from, attendanceRange.to, propertyId);
    const rainfall = await first(env, `SELECT COALESCE(SUM(r.rain_amount),0) total, COUNT(*) entries FROM raindetails r LEFT JOIN blocks b ON b.block_id = r.block_id WHERE date(r.date_time) BETWEEN date(?) AND date(?) AND COALESCE(r.property_id,b.property_id) = ?`, rainfallRange.from, rainfallRange.to, propertyId);
    const yieldTotal = await first(env, `SELECT COALESCE(SUM(ys.yield_quantity),0) quantity, COUNT(*) entries, ROUND(COALESCE(SUM(ys.yield_quantity * COALESCE(yr.yieldrate_running_rate,0)),0),2) value FROM yield_settlement ys JOIN yieldrate yr ON yr.yieldrate_id = ys.yieldrate_id JOIN plantdetails pd ON pd.plant_id = yr.plant_id WHERE date(ys.yield_settlement_date) BETWEEN date(?) AND date(?) AND pd.property_id = ?`, yieldRange.from, yieldRange.to, propertyId);
    const expenses = await first(env, `SELECT ROUND(COALESCE(SUM(other_expense),0),2) total, COUNT(*) entries FROM running_expenses WHERE date(expense_occurence_date) BETWEEN date(?) AND date(?) AND property_id = ?`, expenseRange.from, expenseRange.to, propertyId);
    const income = await first(env, `SELECT ROUND(COALESCE(SUM(ci.income_amount),0),2) total, COUNT(*) entries FROM crop_income ci JOIN cropdetails cd ON cd.crop_id = ci.crop_id WHERE date(ci.received_date) BETWEEN date(?) AND date(?) AND cd.property_id = ?`, incomeRange.from, incomeRange.to, propertyId);
    const assets = await first(env, `SELECT ROUND(COALESCE(SUM(asset_price),0),2) value, COUNT(*) entries FROM currentasset WHERE COALESCE(isactive,1) = 1 AND property_id = ?`, propertyId);
    const plantInventoryTotal = await first(env, `SELECT COALESCE(SUM(plant_count),0) total_plants, COUNT(*) entries FROM plant_inventory WHERE property_id = ?`, propertyId);
    const plantByBlock = await all(env, `SELECT b.block_name, COALESCE(SUM(pi.plant_count),0) plant_count FROM plant_inventory pi JOIN blocks b ON b.block_id = pi.block_id WHERE pi.property_id = ? GROUP BY b.block_id, b.block_name ORDER BY plant_count DESC`, propertyId);
    const plantBySubBlock = await all(env, `SELECT b.block_name, COALESCE(NULLIF(pi.sub_block_name,''),'No sub-block') sub_block_name, COALESCE(SUM(pi.plant_count),0) plant_count FROM plant_inventory pi JOIN blocks b ON b.block_id = pi.block_id WHERE pi.property_id = ? GROUP BY b.block_name, COALESCE(NULLIF(pi.sub_block_name,''),'No sub-block') ORDER BY plant_count DESC`, propertyId);
    const plantByType = await all(env, `SELECT vm.variety_name plant_type, COALESCE(SUM(pi.plant_count),0) plant_count FROM plant_inventory pi JOIN variety_master vm ON vm.variety_master_id=pi.variety_master_id WHERE pi.property_id = ? GROUP BY vm.variety_master_id, vm.variety_name ORDER BY plant_count DESC`, propertyId);
    const profitLabor = await first(env, `SELECT ROUND(COALESCE(SUM(a.attendance_value * COALESCE(w.wage_fixed + w.wage_variable,0)),0),2) total FROM attendance a LEFT JOIN wage w ON w.wage_id=(SELECT w2.wage_id FROM wage w2 WHERE w2.labor_id=a.labor_id ORDER BY datetime(COALESCE(w2.modified_on,w2.created_on)) DESC,w2.wage_id DESC LIMIT 1) WHERE date(a.entry_date) BETWEEN date(?) AND date(?) AND a.property_id = ?`, profitRange.from, profitRange.to, propertyId);
    const profitExpenses = await first(env, `SELECT ROUND(COALESCE(SUM(other_expense),0),2) total FROM running_expenses WHERE date(expense_occurence_date) BETWEEN date(?) AND date(?) AND property_id = ?`, profitRange.from, profitRange.to, propertyId);
    const profitIncome = await first(env, `SELECT ROUND(COALESCE(SUM(sale_value),0),2) total FROM finance_sale WHERE status='confirmed' AND date(sale_date) BETWEEN date(?) AND date(?) AND property_id=?`, profitRange.from, profitRange.to, propertyId);
    const profitYield = { total: 0 };
    const profit = { total: Number(profitIncome?.total || 0) - Number(profitExpenses?.total || 0) };
    const recentAttendance = await all(env, `SELECT a.attendance_id, date(a.entry_date) entry_date, l.name AS labor_name, p.property_name, a.attendance_value, ROUND(a.attendance_value * COALESCE(w.wage_fixed + w.wage_variable,0), 2) cost FROM attendance a JOIN labors l ON l.labor_id = a.labor_id LEFT JOIN wage w ON w.wage_id=(SELECT w2.wage_id FROM wage w2 WHERE w2.labor_id=l.labor_id ORDER BY datetime(COALESCE(w2.modified_on,w2.created_on)) DESC,w2.wage_id DESC LIMIT 1) JOIN property p ON p.property_id = a.property_id WHERE date(a.entry_date) BETWEEN date(?) AND date(?) AND a.property_id = ? ORDER BY a.entry_date DESC, a.attendance_id DESC LIMIT 8`, recentRange.from, recentRange.to, propertyId);
    const rainByBlock = await all(env, `SELECT p.property_name, COALESCE(b.block_name,'Property level') block_name, COALESCE(SUM(r.rain_amount),0) total_rain FROM raindetails r LEFT JOIN blocks b ON b.block_id = r.block_id JOIN property p ON p.property_id = COALESCE(r.property_id,b.property_id) WHERE date(r.date_time) BETWEEN date(?) AND date(?) AND COALESCE(r.property_id,b.property_id) = ? GROUP BY p.property_name, COALESCE(b.block_name,'Property level') ORDER BY total_rain DESC`, rainfallRange.from, rainfallRange.to, propertyId);
    const propertyProfit = await all(env, `SELECT p.property_id,p.property_name,
      (SELECT ROUND(COALESCE(SUM(ci.income_amount),0),2) FROM crop_income ci JOIN cropdetails cd ON cd.crop_id=ci.crop_id WHERE cd.property_id=p.property_id AND date(ci.received_date) BETWEEN date(?) AND date(?)) income,
      (SELECT ROUND(COALESCE(SUM(re.other_expense),0),2) FROM running_expenses re WHERE re.property_id=p.property_id AND date(re.expense_occurence_date) BETWEEN date(?) AND date(?)) expense
      FROM property p WHERE p.property_id=? ORDER BY p.property_name`,profitRange.from,profitRange.to,profitRange.from,profitRange.to,propertyId);
    const workAssignmentTotal = await first(env, `SELECT COUNT(*) entries, COUNT(DISTINCT labor_id) labor_count FROM work_assignment WHERE date(work_date) BETWEEN date(?) AND date(?) AND property_id = ?`, workRange.from, workRange.to, propertyId);
    const todayWork=await first(env,`SELECT COUNT(*) count FROM work_assignment WHERE property_id=? AND date(work_date)=date('now')`,propertyId);
    const activeLabour=await first(env,`SELECT COUNT(DISTINCT labor_id) count FROM attendance WHERE property_id=? AND date(entry_date)=date('now') AND attendance_value>0`,propertyId);
    const monthlyExpense=await first(env,`SELECT ROUND(COALESCE(SUM(other_expense),0),2) total FROM running_expenses WHERE property_id=? AND strftime('%Y-%m',expense_occurence_date)=strftime('%Y-%m','now')`,propertyId);
    const lowStock=await first(env,`SELECT COUNT(*) count FROM fertilizer_master fm LEFT JOIN fertilizer_stock_balance fs ON fs.fertilizer_master_id=fm.fertilizer_master_id AND fs.property_id=? WHERE COALESCE(fm.is_active,1)=1 AND COALESCE(fs.quantity_base,0)<=COALESCE(fm.minimum_stock_base,0)`,propertyId);
    const estateOverview=await first(env,`SELECT COUNT(*) active_blocks,COALESCE(SUM(block_area),0) block_area FROM blocks WHERE property_id=? AND parent_block_id IS NULL`,propertyId);
    const rainMonth=await first(env,`SELECT COALESCE(SUM(r.rain_amount),0) total FROM raindetails r LEFT JOIN blocks b ON b.block_id=r.block_id WHERE COALESCE(r.property_id,b.property_id)=? AND strftime('%Y-%m',r.date_time)=strftime('%Y-%m','now')`,propertyId);
    const mainCrops=await all(env,`SELECT crop_name FROM crop_master WHERE property_id=? ORDER BY crop_name LIMIT 3`,propertyId);
    const upcomingWork=await all(env,`SELECT wa.work_assignment_id,wa.work_date,a.work_activity_name FROM work_assignment wa JOIN work_activity a ON a.work_activity_id=wa.work_activity_id WHERE wa.property_id=? AND date(wa.work_date)>date('now') AND date(wa.work_date)<=date('now','+2 day') ORDER BY wa.work_date LIMIT 20`,propertyId);
    return json({ ranges: { attendance: attendanceRange, rainfall: rainfallRange, yield: yieldRange, expenses: expenseRange, income: incomeRange, assets: assetRange, profit: profitRange, recent: recentRange, work: workRange }, attendance, laborCost, rainfall, yieldTotal, expenses, income, assets, profit, plantInventoryTotal, plantByBlock, plantBySubBlock, plantByType, workAssignmentTotal, recentAttendance, rainByBlock, propertyProfit,management:{todayWork:todayWork?.count||0,activeLabour:activeLabour?.count||0,monthlyExpense:monthlyExpense?.total||0,lowStock:lowStock?.count||0,activeBlocks:estateOverview?.active_blocks||0,blockArea:estateOverview?.block_area||0,rainMonth:rainMonth?.total||0,mainCrops:mainCrops.map(x=>x.crop_name),upcomingWork} });
  } catch (err) { return fail(err, 'Dashboard failed'); }
}
