import { all, first, json, body, propertyIdFromUrl, userIdFromRequest, assertPropertyAccess } from './http.js';

export async function financeContext(request, env) {
  const userId = await userIdFromRequest(request, env);
  const propertyId = propertyIdFromUrl(request);
  if (!propertyId) throw Object.assign(new Error('Select a property first'), { status: 400 });
  await assertPropertyAccess(env, userId, propertyId);
  return { userId, propertyId };
}
async function season(env, propertyId, seasonId) {
  if (!seasonId) return null;
  const value = await first(env, 'SELECT * FROM finance_season WHERE season_id=? AND property_id=?', Number(seasonId), propertyId);
  if (!value) throw Object.assign(new Error('Season does not belong to selected property'), { status: 400 });
  return value;
}
async function crop(env, propertyId, cropId) {
  const value = await first(env, 'SELECT crop_id FROM crop_master WHERE crop_id=? AND property_id=?', Number(cropId), propertyId);
  if (!value) throw Object.assign(new Error('Crop does not belong to selected property'), { status: 400 });
}
async function yieldType(env, cropId, varietyId, yieldTypeId) {
  const value = await first(env, `SELECT fyt.finance_yield_type_id FROM finance_yield_type fyt JOIN variety_master vm ON vm.variety_master_id=fyt.variety_master_id JOIN crop_type_master ct ON ct.crop_type_id=vm.crop_type_id WHERE fyt.finance_yield_type_id=? AND vm.variety_master_id=? AND ct.crop_id=?`, Number(yieldTypeId), Number(varietyId), Number(cropId));
  if (!value) throw Object.assign(new Error('Yield type, variety and crop do not match'), { status: 400 });
}
const amount = (value, label, positive=false) => { const n=Number(value); if(!Number.isFinite(n)||(positive?n<=0:n<0)) throw Object.assign(new Error(`${label} is invalid`),{status:400}); return n; };

export async function financeOverview(env, propertyId, seasonId) {
  await season(env,propertyId,seasonId);
  const args=seasonId?[propertyId,Number(seasonId)]:[propertyId]; const filter=seasonId?'AND season_id=?':'';
  const revenue=(await first(env,`SELECT ROUND(COALESCE(SUM(sale_value),0),2) total FROM finance_sale WHERE property_id=? AND status='confirmed' ${filter}`,...args))?.total||0;
  const expenses=(await first(env,`SELECT ROUND(COALESCE(SUM(other_expense),0),2) total FROM running_expenses WHERE property_id=? AND status='confirmed' ${filter}`,...args))?.total||0;
  const labour=await first(env,`SELECT ROUND(COALESCE(SUM(total_earned),0),2) earned,ROUND(COALESCE(SUM(advance_paid),0),2) advance,ROUND(COALESCE(SUM(settled_paid),0),2) paid,ROUND(COALESCE(SUM(outstanding_balance),0),2) outstanding FROM finance_wage_period WHERE property_id=? AND status IN ('finalized','paid') ${filter}`,...args);
  const vendor=await first(env,`SELECT ROUND(COALESCE(SUM(commission_earned),0),2) earned,ROUND(COALESCE(SUM(paid_amount),0),2) paid,ROUND(COALESCE(SUM(outstanding_balance),0),2) outstanding FROM finance_vendor_period WHERE property_id=? AND status IN ('finalized','paid') ${filter}`,...args);
  const expenseBreakdown=await all(env,`SELECT et.expense_code code,et.expense_name name,ROUND(SUM(re.other_expense),2) total FROM running_expenses re JOIN expensetype et ON et.expensetype_id=re.expensetype_id WHERE re.property_id=? AND re.status='confirmed' ${seasonId?'AND re.season_id=?':''} GROUP BY et.expensetype_id ORDER BY total DESC`,...args);
  const stock=await all(env,`SELECT fyt.finance_yield_type_id,fyt.yield_type_name,vm.variety_name,bu.baseunit_name,ROUND(COALESCE(h.harvested,0),2) harvested,ROUND(COALESCE(s.sold,0),2) sold,ROUND(COALESCE(h.harvested,0)-COALESCE(s.sold,0),2) available FROM finance_yield_type fyt JOIN variety_master vm ON vm.variety_master_id=fyt.variety_master_id JOIN crop_type_master ct ON ct.crop_type_id=vm.crop_type_id JOIN crop_master cm ON cm.crop_id=ct.crop_id JOIN baseunit bu ON bu.baseunit_id=fyt.default_unit_id LEFT JOIN (SELECT finance_yield_type_id,unit_id,SUM(quantity) harvested FROM finance_harvest WHERE property_id=? AND status='confirmed' ${filter} GROUP BY finance_yield_type_id,unit_id) h ON h.finance_yield_type_id=fyt.finance_yield_type_id AND h.unit_id=fyt.default_unit_id LEFT JOIN (SELECT finance_yield_type_id,unit_id,SUM(quantity) sold FROM finance_sale WHERE property_id=? AND status='confirmed' ${filter} GROUP BY finance_yield_type_id,unit_id) s ON s.finance_yield_type_id=fyt.finance_yield_type_id AND s.unit_id=fyt.default_unit_id WHERE cm.property_id=? AND (COALESCE(h.harvested,0)<>0 OR COALESCE(s.sold,0)<>0) ORDER BY vm.variety_name,fyt.yield_type_name`,...(seasonId?[propertyId,Number(seasonId),propertyId,Number(seasonId),propertyId]:[propertyId,propertyId,propertyId]));
  return {revenue,expenses,gain:Number((revenue-expenses).toFixed(2)),labour:labour||{},vendor:vendor||{},stock,expenseBreakdown,currentPrices:[]};
}

export async function financeSetup(env, propertyId) {
  return {
    seasons:await all(env,`SELECT fs.*,cm.crop_name FROM finance_season fs JOIN crop_master cm ON cm.crop_id=fs.crop_id WHERE fs.property_id=? ORDER BY date(fs.start_date) DESC`,propertyId),
    cycles:await all(env,`SELECT * FROM finance_settlement_cycle WHERE property_id=? ORDER BY status,cycle_name`,propertyId),
    engagements:await all(env,`SELECT e.*,l.name labor_name,v.vendorname FROM finance_labour_engagement e JOIN labors l ON l.labor_id=e.labor_id LEFT JOIN vendor v ON v.vendor_id=e.vendor_id WHERE e.property_id=? ORDER BY l.name`,propertyId),
    wageRules:await all(env,`SELECT wr.*,l.name labor_name,fs.season_name,bu.baseunit_name FROM finance_wage_rule wr JOIN labors l ON l.labor_id=wr.labor_id LEFT JOIN finance_season fs ON fs.season_id=wr.season_id LEFT JOIN baseunit bu ON bu.baseunit_id=wr.variable_unit_id WHERE wr.property_id=? ORDER BY date(wr.effective_from) DESC`,propertyId),
    commissionRules:await all(env,`SELECT cr.*,l.name labor_name,v.vendorname,fs.season_name FROM finance_vendor_commission_rule cr JOIN finance_labour_engagement e ON e.labour_engagement_id=cr.labour_engagement_id JOIN labors l ON l.labor_id=e.labor_id JOIN vendor v ON v.vendor_id=e.vendor_id LEFT JOIN finance_season fs ON fs.season_id=cr.season_id WHERE cr.property_id=? ORDER BY date(cr.effective_from) DESC`,propertyId),
    yieldTypes:await all(env,`SELECT fyt.*,vm.variety_name,ct.type_name,cm.crop_name,bu.baseunit_name FROM finance_yield_type fyt JOIN variety_master vm ON vm.variety_master_id=fyt.variety_master_id JOIN crop_type_master ct ON ct.crop_type_id=vm.crop_type_id JOIN crop_master cm ON cm.crop_id=ct.crop_id JOIN baseunit bu ON bu.baseunit_id=fyt.default_unit_id WHERE cm.property_id=? ORDER BY cm.crop_name,vm.variety_name,fyt.yield_type_name`,propertyId),
    buyers:await all(env,`SELECT vendor_id buyer_id,vendorname buyer_name,description FROM vendor WHERE user_id=(SELECT user_id FROM property WHERE property_id=?) ORDER BY vendorname`,propertyId)
  };
}
const lists={
  seasons:`SELECT fs.*,cm.crop_name FROM finance_season fs JOIN crop_master cm ON cm.crop_id=fs.crop_id WHERE fs.property_id=? ORDER BY date(fs.start_date) DESC`,
  expenses:`SELECT re.*,et.expense_name,et.expense_code FROM running_expenses re JOIN expensetype et ON et.expensetype_id=re.expensetype_id WHERE re.property_id=?`,
  harvests:`SELECT h.*,vm.variety_name,fyt.yield_type_name,bu.baseunit_name FROM finance_harvest h JOIN variety_master vm ON vm.variety_master_id=h.variety_master_id JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=h.finance_yield_type_id JOIN baseunit bu ON bu.baseunit_id=h.unit_id WHERE h.property_id=?`,
  marketRates:`SELECT mr.*,vm.variety_name,fyt.yield_type_name,bu.baseunit_name FROM finance_market_rate mr JOIN variety_master vm ON vm.variety_master_id=mr.variety_master_id JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=mr.finance_yield_type_id JOIN baseunit bu ON bu.baseunit_id=mr.unit_id WHERE mr.property_id=?`,
  buyerOffers:`SELECT bo.*,v.vendorname buyer_name,vm.variety_name,fyt.yield_type_name,bu.baseunit_name FROM finance_buyer_offer bo JOIN vendor v ON v.vendor_id=bo.buyer_id JOIN variety_master vm ON vm.variety_master_id=bo.variety_master_id JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=bo.finance_yield_type_id JOIN baseunit bu ON bu.baseunit_id=bo.unit_id WHERE bo.property_id=?`,
  sales:`SELECT s.*,v.vendorname buyer_name,vm.variety_name,fyt.yield_type_name,bu.baseunit_name FROM finance_sale s JOIN vendor v ON v.vendor_id=s.buyer_id JOIN variety_master vm ON vm.variety_master_id=s.variety_master_id JOIN finance_yield_type fyt ON fyt.finance_yield_type_id=s.finance_yield_type_id JOIN baseunit bu ON bu.baseunit_id=s.unit_id WHERE s.property_id=?`,
  wagePeriods:`SELECT wp.*,l.name labor_name FROM finance_wage_period wp JOIN labors l ON l.labor_id=wp.labor_id WHERE wp.property_id=?`,
  vendorPeriods:`SELECT vp.*,l.name labor_name,v.vendorname FROM finance_vendor_period vp JOIN labors l ON l.labor_id=vp.labor_id JOIN vendor v ON v.vendor_id=vp.vendor_id WHERE vp.property_id=?`
};
export async function financeList(env,propertyId,resource,seasonId){ const sql=lists[resource]; if(!sql)return null; await season(env,propertyId,seasonId); const aliases={expenses:'re',harvests:'h',marketRates:'mr',buyerOffers:'bo',sales:'s',wagePeriods:'wp',vendorPeriods:'vp'}; return all(env,`${sql} ${seasonId&&aliases[resource]?'AND '+aliases[resource]+'.season_id=?':''} ORDER BY 1 DESC`,...(seasonId&&aliases[resource]?[propertyId,Number(seasonId)]:[propertyId])); }

export async function financeCreate(request,env,propertyId,resource){
  const b=await body(request),who=String(b.created_by||'Owner').slice(0,80); if(b.season_id)await season(env,propertyId,b.season_id); let stmt,values;
  if(resource==='seasons'){await crop(env,propertyId,b.crop_id);stmt=`INSERT INTO finance_season(property_id,crop_id,season_name,start_date,end_date,status,created_by) VALUES(?,?,?,?,?,?,?)`;values=[propertyId,b.crop_id,b.season_name,b.start_date,b.end_date,b.status||'planned',who];}
  else if(resource==='cycles'){stmt=`INSERT INTO finance_settlement_cycle(property_id,cycle_name,frequency,custom_days,effective_from,effective_to,created_by) VALUES(?,?,?,?,?,?,?)`;values=[propertyId,b.cycle_name,b.frequency,b.custom_days||null,b.effective_from,b.effective_to||null,who];}
  else if(resource==='engagements'){stmt=`INSERT INTO finance_labour_engagement(property_id,labor_id,labour_type,vendor_id,effective_from,effective_to,created_by) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM propertylabor WHERE property_id=? AND labor_id=?)`;values=[propertyId,b.labor_id,b.labour_type,b.labour_type==='vendor'?b.vendor_id:null,b.effective_from,b.effective_to||null,who,propertyId,b.labor_id];}
  else if(resource==='wageRules'){stmt=`INSERT INTO finance_wage_rule(property_id,season_id,labor_id,settlement_cycle_id,effective_from,effective_to,fixed_rate,fixed_basis,variable_rate,variable_unit_id,overtime_rate,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`;values=[propertyId,b.season_id||null,b.labor_id,b.settlement_cycle_id||null,b.effective_from,b.effective_to||null,amount(b.fixed_rate||0,'Fixed rate'),b.fixed_basis||'day',amount(b.variable_rate||0,'Variable rate'),b.variable_unit_id||null,amount(b.overtime_rate||0,'Overtime rate'),who];}
  else if(resource==='commissionRules'){stmt=`INSERT INTO finance_vendor_commission_rule(property_id,season_id,labour_engagement_id,effective_from,effective_to,commission_percentage,created_by) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM finance_labour_engagement WHERE labour_engagement_id=? AND property_id=? AND labour_type='vendor')`;values=[propertyId,b.season_id||null,b.labour_engagement_id,b.effective_from,b.effective_to||null,amount(b.commission_percentage,'Commission'),who,b.labour_engagement_id,propertyId];}
  else if(resource==='yieldTypes'){await crop(env,propertyId,b.crop_id);stmt=`INSERT INTO finance_yield_type(variety_master_id,yield_type_name,default_unit_id,created_by) VALUES(?,?,?,?)`;values=[b.variety_master_id,b.yield_type_name,b.default_unit_id,who];}
  else if(resource==='marketRates'){await crop(env,propertyId,b.crop_id);await yieldType(env,b.crop_id,b.variety_master_id,b.finance_yield_type_id);stmt=`INSERT INTO finance_market_rate(property_id,season_id,crop_id,variety_master_id,finance_yield_type_id,effective_date,rate,unit_id,source_name,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)`;values=[propertyId,b.season_id||null,b.crop_id,b.variety_master_id,b.finance_yield_type_id,b.effective_date,amount(b.rate,'Rate'),b.unit_id,b.source_name||null,b.notes||null,who];}
  else if(resource==='buyerOffers'){await crop(env,propertyId,b.crop_id);await yieldType(env,b.crop_id,b.variety_master_id,b.finance_yield_type_id);stmt=`INSERT INTO finance_buyer_offer(property_id,season_id,crop_id,variety_master_id,finance_yield_type_id,buyer_id,market_rate_id,offered_rate,unit_id,offer_date,valid_until,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`;values=[propertyId,b.season_id||null,b.crop_id,b.variety_master_id,b.finance_yield_type_id,b.buyer_id,b.market_rate_id||null,amount(b.offered_rate,'Offered rate'),b.unit_id,b.offer_date,b.valid_until||null,b.notes||null,who];}
  else if(resource==='harvests'){await crop(env,propertyId,b.crop_id);await yieldType(env,b.crop_id,b.variety_master_id,b.finance_yield_type_id);stmt=`INSERT INTO finance_harvest(property_id,season_id,crop_id,variety_master_id,finance_yield_type_id,block_id,quantity,unit_id,harvest_date,notes,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`;values=[propertyId,b.season_id,b.crop_id,b.variety_master_id,b.finance_yield_type_id,b.block_id||null,amount(b.quantity,'Quantity',true),b.unit_id,b.harvest_date,b.notes||null,b.status||'confirmed',who];}
  else if(resource==='sales'){await crop(env,propertyId,b.crop_id);await yieldType(env,b.crop_id,b.variety_master_id,b.finance_yield_type_id);const q=amount(b.quantity,'Quantity',true),rate=amount(b.actual_rate,'Actual rate');stmt=`INSERT INTO finance_sale(property_id,season_id,crop_id,variety_master_id,finance_yield_type_id,buyer_id,market_rate_id,buyer_offer_id,quantity,unit_id,actual_rate,sale_value,sale_date,payment_status,payment_method,notes,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;values=[propertyId,b.season_id,b.crop_id,b.variety_master_id,b.finance_yield_type_id,b.buyer_id,b.market_rate_id||null,b.buyer_offer_id||null,q,b.unit_id,rate,Number((q*rate).toFixed(2)),b.sale_date,b.payment_status||'unpaid',b.payment_method||null,b.notes||null,b.status||'confirmed',who];}
  else if(resource==='expenses'){stmt=`INSERT INTO running_expenses(expensetype_id,property_id,season_id,crop_master_id,block_id,work_activity_id,finance_yield_type_id,expense_code,expense_occurence_date,other_expense,description,payment_status,payment_method,source_type,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'manual','confirmed',?)`;values=[b.expensetype_id,propertyId,b.season_id||null,b.crop_id||null,b.block_id||null,b.work_activity_id||null,b.finance_yield_type_id||null,b.description,b.expense_date,b.amount,b.description,b.payment_status||'paid',b.payment_method||null,who];}
  else if(resource==='wagePeriods'){const total=amount(b.total_earned,'Total earned'),advance=amount(b.advance_paid||0,'Advance'),paid=amount(b.settled_paid||0,'Paid'),outstanding=Number((total-advance-paid).toFixed(2));if(outstanding<0)throw Object.assign(new Error('Advance and paid amount cannot exceed total earned'),{status:400});stmt=`INSERT INTO finance_wage_period(property_id,season_id,labor_id,wage_rule_id,settlement_cycle_id,period_start,period_end,fixed_earned,variable_earned,overtime_earned,total_earned,advance_paid,settled_paid,outstanding_balance,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;values=[propertyId,b.season_id||null,b.labor_id,b.wage_rule_id,b.settlement_cycle_id||null,b.period_start,b.period_end,b.fixed_earned||0,b.variable_earned||0,b.overtime_earned||0,total,advance,paid,outstanding,who];}
  else if(resource==='vendorPeriods'){const wage=await first(env,`SELECT * FROM finance_wage_period WHERE wage_period_id=? AND property_id=? AND status IN ('finalized','paid')`,b.wage_period_id,propertyId),rule=await first(env,`SELECT cr.*,e.vendor_id,e.labor_id FROM finance_vendor_commission_rule cr JOIN finance_labour_engagement e ON e.labour_engagement_id=cr.labour_engagement_id WHERE cr.vendor_commission_rule_id=? AND cr.property_id=? AND e.labour_type='vendor'`,b.vendor_commission_rule_id,propertyId);if(!wage||!rule||Number(wage.labor_id)!==Number(rule.labor_id))throw Object.assign(new Error('Commission rule does not match a finalized wage period'),{status:400});const commission=Number((Number(wage.total_earned)*Number(rule.commission_percentage)/100).toFixed(2)),paid=amount(b.paid_amount||0,'Paid amount');if(paid>commission)throw Object.assign(new Error('Paid amount cannot exceed commission earned'),{status:400});stmt=`INSERT INTO finance_vendor_period(property_id,season_id,vendor_id,labor_id,wage_period_id,vendor_commission_rule_id,period_start,period_end,eligible_earnings,commission_percentage,commission_earned,paid_amount,outstanding_balance,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;values=[propertyId,wage.season_id,rule.vendor_id,wage.labor_id,wage.wage_period_id,rule.vendor_commission_rule_id,wage.period_start,wage.period_end,wage.total_earned,rule.commission_percentage,commission,paid,Number((commission-paid).toFixed(2)),who];}
  else return json({error:'Unsupported finance resource'},404);
  const result=await env.DB.prepare(stmt).bind(...values).run(); return json({id:Number(result.meta.last_row_id)},201);
}
