export const rateHelp = {
  daily: 'Daily Wages are the estate default amounts for a full day or half day of attendance. They apply to everyone unless a dated labour exception or seasonal wage applies.',
  work: 'Work Rates are extra charges for assigned work, such as an amount per acre or tree. Salary uses the rate for the work date and the quantity recorded in Work Assignment.',
  seasonal: 'Seasonal rates apply only within their From and To dates. A labour-specific daily wage takes priority when present. Seasonal rates can change other daily wages and pay a one-time bonus when the harvest quantity reaches the minimum. Seasonal bonus rules remain estate-wide.',
  overtime: 'Overtime covers extra hours or other charges, such as transport trips. Set the rate here; record the actual hours or quantity in Salary Settlement.',
  exceptions: 'Labour Exceptions are optional negotiated rates for individual people. Only the selected component changes; all other components continue using estate defaults. Each exception has its own date range.',
  period: 'From Date and To Date are inclusive. Salary uses the version that covers the work date. Save a new, non-overlapping date range when a rate changes; previous rates and paid salaries stay unchanged.',
  history: 'Rate History retains every dated version. Active means it applies today; Upcoming starts later; Expired has ended. Copy a version to a new date range instead of changing the old one.',
};
export const financeHelp = {
  Overview: 'A summary of estate income, expenses, labour payments and vendor commission for the selected crop season.',
  'Labour Salary': 'View salary payment history, breakdowns and reports. Paid amounts come from saved settlement records. To calculate or pay salary, open Salary Settlement from Home.',
  'Vendor & Labour Setup': 'Manage labour details and vendor links, and view labour and vendor totals. Set wage amounts in Set Rates.',
  Expenses: 'Record estate spending and review expenses. Salary payments create their own expense records, so do not enter the same salary again here.',
  'Yield & Sales': 'Record harvested produce, quantities sold and selling prices. These are estate totals; worker harvest quantities used for bonuses are recorded in Salary Settlement.',
  'Season Summary': 'Review income, costs and gain for a crop season. A crop season groups estate activity; it is different from a seasonal wage rate.',
  'Market Configuration': 'Maintain market reference prices and buyer details used when recording produce sales.',
  'Finance Setup': 'Maintain crop seasons, payment periods, commission rules and expense or yield categories. Wage rates are maintained in Set Rates.',
  'Season Management': 'Define crop seasons for grouping harvest, sales and costs. Seasonal wage rates are configured separately under Set Rates.',
  'Settlement Cycle': 'A salary settlement cycle is the period used to group wages, such as weekly, every 15 days or monthly. It does not set the wage or automatically pay anyone. The Salary Settlement screen can mark individual work days as paid.',
  'Settlement Cycles': 'Define weekly, 15-day, monthly or custom salary periods. A cycle groups dates; it does not set a daily wage or make an automatic payment.',
  'Vendor Commission': 'Set the percentage owed to a vendor for linked labour. This is a vendor charge, separate from the labourer\'s daily wage.',
  'Vendor Commission Rules': 'Set a dated commission percentage for vendor-linked labour. This controls the vendor charge, not the labourer\'s wage.',
  'Expense Types': 'Categories for spending, such as fuel, maintenance or labour. They help organise expense reports.',
  'Yield Types': 'Forms of produce, such as cherry or parchment, with their measurement units. Stock and sale quantities are tracked separately for each form.',
  'Market Rates': 'Reference prices for produce. A reference price helps compare offers; it does not replace the actual price recorded for a sale.',
  Buyers: 'People or businesses that buy produce from the estate. Select a buyer when recording an offer or sale.',
  Vendors: 'People or businesses supplying labour or services to the estate.',
  'Labour Setup': 'Maintain labourer details and link vendor-supplied labour to the correct vendor.',
  'Salary payment history': 'Review saved salary payments and reports, including the rates and deductions used at payment time.',
};
